# Generated by Django 5.2 on 2025-05-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_register_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='User',
        ),
    ]
