# Generated by Django 5.2 on 2025-05-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
