# Generated by Django 5.2 on 2025-05-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('add_blog', models.CharField(max_length=1000)),
                ('checking', models.BooleanField(default=False)),
            ],
        ),
    ]
