# Generated by Django 5.2 on 2025-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thought', models.CharField(verbose_name=250)),
                ('checking', models.BooleanField(default=False)),
            ],
        ),
    ]
